# apisix-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apisix:3.11.0
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        env:
        - name: APISIX_DEPLOYMENT
          value: "minikube"
        - name: ETCD_HOST
          value: "etcd"
        - name: ETCD_HOSTS
          value: "http://etcd:2379"
        - name: ETCD_PORT
          value: "2379"
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30080
    name: http
  - port: 9443
    targetPort: 9443
    nodePort: 30443
    name: https
  selector:
    app: apisix