apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: apisix:3.11.0
          ports:
            - containerPort: 9080
            - containerPort: 9443
          env:
            - name: ETCD_HOSTS
              value: "http://10.97.92.215:2379"
            - name: APISIX_ETCD_HOSTS
              value: "http://10.97.92.215:2379"
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  ports:
    - port: 80
      targetPort: 9080
  selector:
    app: apisix