# etcd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd:latest
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd:2379"
        ports:
        - containerPort: 2379
        - containerPort: 2380
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: etcd